from word_lists import *

def build_chosen_word_str(unit_num, lesson_num):
    if unit_num == '1':
        if lesson_num == '1':
            chosen_word_str = ', '.join(l2_u1_l1_list)
        elif lesson_num == '2':
            chosen_word_str = ', '.join(l2_u1_l2_list)
        elif lesson_num == '3':
            chosen_word_str = ', '.join(l2_u1_l3_list)
        elif lesson_num == '4':
            chosen_word_str = ', '.join(l2_u1_l4_list)
    elif unit_num == '2':
        if lesson_num == '1':
            chosen_word_str = ', '.join(l2_u2_l1_list)
        elif lesson_num == '2':
            chosen_word_str = ', '.join(l2_u2_l2_list)
        elif lesson_num == '3':
            chosen_word_str = ', '.join(l2_u2_l3_list)
        elif lesson_num == '4':
            chosen_word_str = ', '.join(l2_u2_l4_list)
    elif unit_num == '3':
        if lesson_num == '1':
            chosen_word_str = ', '.join(l2_u3_l1_list)
        elif lesson_num == '2':
            chosen_word_str = ', '.join(l2_u3_l2_list)
        elif lesson_num == '3':
            chosen_word_str = ', '.join(l2_u3_l3_list)
        elif lesson_num == '4':
            chosen_word_str = ', '.join(l2_u3_l4_list)
    elif unit_num == '4':
        if lesson_num == '1':
            chosen_word_str = ', '.join(l2_u4_l1_list)
        elif lesson_num == '2':
            chosen_word_str = ', '.join(l2_u4_l2_list)
        elif lesson_num == '3':
            chosen_word_str = ', '.join(l2_u4_l3_list)
        elif lesson_num == '4':
            chosen_word_str = ', '.join(l2_u4_l4_list)
    elif unit_num == '5':
        if lesson_num == '1':
            chosen_word_str = ', '.join(l2_u5_l1_list)
        elif lesson_num == '2':
            chosen_word_str = ', '.join(l2_u5_l2_list)
        elif lesson_num == '3':
            chosen_word_str = ', '.join(l2_u5_l3_list)
        elif lesson_num == '4':
            chosen_word_str = ', '.join(l2_u5_l4_list)
    elif unit_num == '6':
        if lesson_num == '1':
            chosen_word_str = ', '.join(l2_u6_l1_list)
        elif lesson_num == '2':
            chosen_word_str = ', '.join(l2_u6_l2_list)
        elif lesson_num == '3':
            chosen_word_str = ', '.join(l2_u6_l3_list)
        elif lesson_num == '4':
            chosen_word_str = ', '.join(l2_u6_l4_list)
    elif unit_num == '7':
        if lesson_num == '1':
            chosen_word_str = ', '.join(l2_u7_l1_list)
        elif lesson_num == '2':
            chosen_word_str = ', '.join(l2_u7_l2_list)
        elif lesson_num == '3':
            chosen_word_str = ', '.join(l2_u7_l3_list)
        elif lesson_num == '4':
            chosen_word_str = ', '.join(l2_u7_l4_list)
    elif unit_num == '8':
        if lesson_num == '1':
            chosen_word_str = ', '.join(l2_u8_l1_list)
        elif lesson_num == '2':
            chosen_word_str = ', '.join(l2_u8_l2_list)
        elif lesson_num == '3':
            chosen_word_str = ', '.join(l2_u8_l3_list)
        elif lesson_num == '4':
            chosen_word_str = ', '.join(l2_u8_l4_list)
    elif unit_num == '9':
        if lesson_num == '1':
            chosen_word_str = ', '.join(l2_u9_l1_list)
        elif lesson_num == '2':
            chosen_word_str = ', '.join(l2_u9_l2_list)
        elif lesson_num == '3':
            chosen_word_str = ', '.join(l2_u9_l3_list)
        elif lesson_num == '4':
            chosen_word_str = ', '.join(l2_u9_l4_list)
    elif unit_num == '10':
        if lesson_num == '1':
            chosen_word_str = ', '.join(l2_u10_l1_list)
        elif lesson_num == '2':
            chosen_word_str = ', '.join(l2_u10_l2_list)
        elif lesson_num == '3':
            chosen_word_str = ', '.join(l2_u10_l3_list)
        elif lesson_num == '4':
            chosen_word_str = ', '.join(l2_u10_l4_list)
    elif unit_num == '11':
        if lesson_num == '1':
            chosen_word_str = ', '.join(l2_u11_l1_list)
        elif lesson_num == '2':
            chosen_word_str = ', '.join(l2_u11_l2_list)
        elif lesson_num == '3':
            chosen_word_str = ', '.join(l2_u11_l3_list)
        elif lesson_num == '4':
            chosen_word_str = ', '.join(l2_u11_l4_list)
    elif unit_num == '12':
        if lesson_num == '1':
            chosen_word_str = ', '.join(l2_u12_l1_list)
        elif lesson_num == '2':
            chosen_word_str = ', '.join(l2_u12_l2_list)
        elif lesson_num == '3':
            chosen_word_str = ', '.join(l2_u12_l3_list)
        elif lesson_num == '4':
            chosen_word_str = ', '.join(l2_u12_l4_list)
    

    return chosen_word_str